name: Django CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV

    - name: Run migrations
      env:
        TEST_ENV: true
      run: python manage.py migrate

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Test SSH connection
        run: ssh -v -o StrictHostKeyChecking=no deploy@example.com "echo SSH connection successful"
        env:
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}

      - name: List files before rsync
        run: |
          echo "Список файлов в GitHub Actions runner перед rsync:"
          ls -la

      - name: Deploy with rsync
        run: rsync -avz -e "ssh -o StrictHostKeyChecking=no" --delete ./ deploy@example.com:/var/www/html
        env:
          SSH_AUTH_SOCK: ${{ env.SSH_AUTH_SOCK }}